# ---
# - ros_topic_name: "/diff_drive/cmd_vel"
#   gz_topic_name: "/model/diff_drive/cmd_vel"
#   ros_type_name: "geometry_msgs/msg/Twist"
#   gz_type_name: "gz.msgs.Twist"
#   direction: ROS_TO_GZ
# - ros_topic_name: "/clock"
#   gz_topic_name: "/clock"
#   ros_type_name: "rosgraph_msgs/msg/Clock"
#   gz_type_name: "gz.msgs.Clock"
#   direction: GZ_TO_ROS
# - ros_topic_name: "/diff_drive/odometry"
#   gz_topic_name: "/model/diff_drive/odometry"
#   ros_type_name: "nav_msgs/msg/Odometry"
#   gz_type_name: "gz.msgs.Odometry"
#   direction: GZ_TO_ROS
# - ros_topic_name: "/diff_drive/scan"
#   gz_topic_name: "/scan"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: GZ_TO_ROS
# - ros_topic_name: "/clock"
#   gz_topic_name: "/clock"
#   ros_type_name: "rosgraph_msgs/msg/clock"
#   gz_type_name: "gz.msgs.Clock"
#   direction: GZ_TO_ROS
# - ros_topic_name: "/joint_states"
#   gz_topic_name: "/world/demo/model/diff_drive/joint_state"
#   ros_type_name: "sensor_msgs/msg/JointState"
#   gz_type_name: "gz.msgs.Model"
#   direction: GZ_TO_ROS
# - ros_topic_name: "/tf"
#   gz_topic_name: "/model/diff_drive/pose"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "gz.msgs.Pose_V"
#   direction: GZ_TO_ROS
# - ros_topic_name: "/tf_static"
#   gz_topic_name: "/model/diff_drive/pose_static"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "gz.msgs.Pose_V"
#   direction: GZ_TO_ROS

ignition_ros2_bridge:
  bridge_name: "laracna_bridge"
  ros2_topics:
    - name: "/laracna/coxa_lb/joint_states"
      type: "sensor_msgs/msg/JointState"
      ign_topic: "/world/demo/model/laracna/joint/coxa_lb_j/state"
    - name: "/laracna/coxa_rb/joint_states"
      type: "sensor_msgs/msg/JointState"
      ign_topic: "/world/demo/model/laracna/joint/coxa_rb_j/state"
    - name: "/laracna/coxa_lt/joint_states"
      type: "sensor_msgs/msg/JointState"
      ign_topic: "/world/demo/model/laracna/joint/coxa_lt_j/state"
    - name: "/laracna/coxa_rt/joint_states"
      type: "sensor_msgs/msg/JointState"
      ign_topic: "/world/demo/model/laracna/joint/coxa_rt_j/state"

    - name: "/laracna/femur_lb/joint_states"
      type: "sensor_msgs/msg/JointState"
      ign_topic: "/world/demo/model/laracna/joint/femur_lb_j/state"
    - name: "/laracna/femur_rb/joint_states"
      type: "sensor_msgs/msg/JointState"
      ign_topic: "/world/demo/model/laracna/joint/femur_rb_j/state"
    - name: "/laracna/femur_lt/joint_states"
      type: "sensor_msgs/msg/JointState"
      ign_topic: "/world/demo/model/laracna/joint/femur_lt_j/state"
    - name: "/laracna/femur_rt/joint_states"
      type: "sensor_msgs/msg/JointState"
      ign_topic: "/world/demo/model/laracna/joint/femur_rt_j/state"

    - name: "/laracna/tibia_lb/joint_states"
      type: "sensor_msgs/msg/JointState"
      ign_topic: "/world/demo/model/laracna/joint/tibia_lb_j/state"
    - name: "/laracna/tibia_rb/joint_states"
      type: "sensor_msgs/msg/JointState"
      ign_topic: "/world/demo/model/laracna/joint/tibia_rb_j/state"
    - name: "/laracna/tibia_lt/joint_states"
      type: "sensor_msgs/msg/JointState"
      ign_topic: "/world/demo/model/laracna/joint/tibia_lt_j/state"
    - name: "/laracna/tibia_rt/joint_states"
      type: "sensor_msgs/msg/JointState"
      ign_topic: "/world/demo/model/laracna/joint/tibia_rt_j/state"

  ignition_topics:
    - name: "/world/demo/model/laracna/joint/coxa_lb_j/state"
      type: "gz.msgs.JointState"
      ros2_topic: "/laracna/coxa_lb/joint_states"
    - name: "/world/demo/model/laracna/joint/coxa_rb_j/state"
      type: "gz.msgs.JointState"
      ros2_topic: "/laracna/coxa_rb/joint_states"
    - name: "/world/demo/model/laracna/joint/coxa_lt_j/state"
      type: "gz.msgs.JointState"
      ros2_topic: "/laracna/coxa_lt/joint_states"
    - name: "/world/demo/model/laracna/joint/coxa_rt_j/state"
      type: "gz.msgs.JointState"
      ros2_topic: "/laracna/coxa_rt/joint_states"

    - name: "/world/demo/model/laracna/joint/femur_lb_j/state"
      type: "gz.msgs.JointState"
      ros2_topic: "/laracna/femur_lb/joint_states"
    - name: "/world/demo/model/laracna/joint/femur_rb_j/state"
      type: "gz.msgs.JointState"
      ros2_topic: "/laracna/femur_rb/joint_states"
    - name: "/world/demo/model/laracna/joint/femur_lt_j/state"
      type: "gz.msgs.JointState"
      ros2_topic: "/laracna/femur_lt/joint_states"
    - name: "/world/demo/model/laracna/joint/femur_rt_j/state"
      type: "gz.msgs.JointState"
      ros2_topic: "/laracna/femur_rt/joint_states"

    - name: "/world/demo/model/laracna/joint/tibia_lb_j/state"
      type: "gz.msgs.JointState"
      ros2_topic: "/laracna/tibia_lb/joint_states"
    - name: "/world/demo/model/laracna/joint/tibia_rb_j/state"
      type: "gz.msgs.JointState"
      ros2
